### ISSUE TITLE
[Question] Support for Minecraft Barrel

### ISSUE THREAD

**Issue by pandwyna** [devs-immortal/chest-colorizer#5]
Hi, great mod! Is there any way to add support for barrels? It would be nice, if you can also add color to a barrel.

**Comment by kalucky0** [comment]
Already working on that

**Comment by sternschnaube** [comment]
Any update on that? @kalucky0 😄

**Comment by kalucky0** [comment]
Ah, sorry. I'm very busy with university projects right now. I will try to do this ASAP though

**Comment by sternschnaube** [comment]
Sounds great!
